### ISSUE TITLE
Why not use form submit?

### ISSUE THREAD

**Issue by ianldgs** [gilf/st-login#1]
with:
```jsx
<form class="login-form" onSubmit={this.login()}>
```

login method could look like this:
```ts
login() {
    this.loginShouldOccur.emit({ username: inputs[0].value, password: inputs[1].value });
}
```

and you can remove the `@Listen('keydown.enter')`

**Comment by gilf** [comment]
Hi @ianldgs,

Thanks for the comment!
While submit is probably the way to go, most of my customers require their own login functionality and ask for an Ajax request. This is why I implemented this form as a all purpose form.

**Comment by ianldgs** [comment]
@gilf you can still make an ajax call when submit happens. You need just to call `event.preventDefault()`

**Comment by gilf** [comment]
Thanks for the comments.
Done! The new version uses submit.
